import type { ModelCatalogEntry, ModelPackId, ModelTaskGroup } from './types'

export const modelPacks: Record<ModelPackId, { label: string; description: string; enabledByDefault: boolean }> = {
  core: {
    label: '核心模型包',
    description: '通用统计、差异检验、相关关系和基础回归。',
    enabledByDefault: true,
  },
  advanced: {
    label: '进阶模型包',
    description: '面板固定效应、高维固定效应和机制检验。',
    enabledByDefault: true,
  },
  experimental: {
    label: '实验模型包',
    description: '空间计量、门槛回归和复杂机制模型；成熟度由各模型 fixture 状态单独标记。',
    enabledByDefault: true,
  },
}

export const modelTaskGroupOrder: ModelTaskGroup[] = ['数据探索', '差异检验', '相关关系', '回归建模', '面板与固定效应', '机制检验', '空间与扩展模型']

const coreAccuracy = '浏览器内 TypeScript 实现，适合常规探索分析；核心数值结果由自动回归测试覆盖。'
const fixedEffectsAccuracy = '浏览器内 TypeScript 固定效应实现；在已覆盖 Stata/reghdfe golden fixture 范围内按逐项一致目标维护。'
const previewAccuracy = '浏览器内轻量实现，适合探索和方案设计；正式论文建议用 Stata/R/Python 复核。'
const experimentalAccuracy = '实验性浏览器实现，默认显示但保留实验标记；结果仅适合方法预览，不应直接作为论文结论。'
const stableSpatialAccuracy = '浏览器内 TypeScript 空间计量实现；SLX/SAR/SEM/SDM 已在 PySAL/spreg fixture 范围内验证，支持 edge-list、方阵 CSV、GAL/GWT 权重。'
const previewSpatialAccuracy = '浏览器内预览实现，未完成 PySAL/spreg fixture 数值验真；适合设定探索，正式论文建议用 PySAL/Stata/R 复核。'

export const modelCatalog: ModelCatalogEntry[] = [
  {
    id: 'frequency-analysis',
    taskGroup: '数据探索',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '查看分类、文本或时间字段的取值分布。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'category-summary',
    taskGroup: '数据探索',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '按组比较数值变量的均值、中位数和波动。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'descriptive-statistics',
    taskGroup: '数据探索',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '批量查看数值变量的样本量、均值和范围。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'variance-analysis',
    taskGroup: '数据探索',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '查看数值变量整体或分组后的离散程度。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'normality-test',
    taskGroup: '数据探索',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '判断数值变量是否明显偏离正态分布。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'independent-t-test',
    taskGroup: '差异检验',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '比较两个独立组的均值差异。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'one-sample-t-test',
    taskGroup: '差异检验',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '检验一个变量的均值是否不同于给定值。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'paired-t-test',
    taskGroup: '差异检验',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '比较同一对象前后或两列配对数据的均值差。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'nonparametric-test',
    taskGroup: '差异检验',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '在分布偏态或不满足 t 检验假设时比较组间差异。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'correlation-analysis',
    taskGroup: '相关关系',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '查看多个数值变量之间的 Pearson 相关关系。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'crosstab-chi-square',
    taskGroup: '相关关系',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '检验两个分类变量是否存在关联。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'linear-regression',
    taskGroup: '回归建模',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '估计一个因变量与多个解释变量之间的线性关系。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'ordinary-regression',
    taskGroup: '回归建模',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '快速执行多元 OLS 回归并查看系数显著性。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'logit-regression',
    taskGroup: '回归建模',
    packId: 'core',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '估计二分类结果发生概率及 Odds Ratio。',
    accuracyNotes: coreAccuracy,
  },
  {
    id: 'xtreg-fixed-effects',
    taskGroup: '面板与固定效应',
    packId: 'advanced',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '控制面板个体固定效应，估计组内变化关系。',
    accuracyNotes: fixedEffectsAccuracy,
  },
  {
    id: 'reghdfe-regression',
    taskGroup: '面板与固定效应',
    packId: 'advanced',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '吸收多维固定效应，适合高维面板或分组数据。',
    accuracyNotes: fixedEffectsAccuracy,
  },
  {
    id: 'mediation-analysis',
    taskGroup: '机制检验',
    packId: 'advanced',
    modelVersion: '0.8.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '分析 X 是否通过中介变量 M 影响 Y。',
    accuracyNotes: previewAccuracy,
  },
  {
    id: 'moderation-analysis',
    taskGroup: '机制检验',
    packId: 'advanced',
    modelVersion: '0.8.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '检验 W 是否改变 X 对 Y 的影响强度。',
    accuracyNotes: previewAccuracy,
  },
  {
    id: 'moderated-mediation',
    taskGroup: '机制检验',
    packId: 'experimental',
    modelVersion: '0.4.0',
    maturityLevel: 'experimental',
    enabledByDefault: true,
    useCase: '检验中介效应是否随调节变量 W 改变。',
    accuracyNotes: experimentalAccuracy,
  },
  {
    id: 'threshold-regression',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.4.0',
    maturityLevel: 'experimental',
    enabledByDefault: true,
    useCase: '寻找门槛变量导致关系结构变化的切点。',
    accuracyNotes: experimentalAccuracy,
  },
  {
    id: 'spatial-sar',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '估计相邻地区因变量的空间滞后影响。',
    accuracyNotes: stableSpatialAccuracy,
  },
  {
    id: 'spatial-slx',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '估计解释变量的邻近空间溢出。',
    accuracyNotes: stableSpatialAccuracy,
  },
  {
    id: 'spatial-sdm',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '同时估计 Wy 和 WX 的空间杜宾模型。',
    accuracyNotes: stableSpatialAccuracy,
  },
  {
    id: 'spatial-sem',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '1.0.0',
    maturityLevel: 'stable',
    enabledByDefault: true,
    useCase: '识别误差项中的空间相关。',
    accuracyNotes: stableSpatialAccuracy,
  },
  {
    id: 'spatial-sdem',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.5.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '同时估计 WX 和误差空间相关。',
    accuracyNotes: previewSpatialAccuracy,
  },
  {
    id: 'spatial-sac',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.5.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '同时估计因变量滞后和误差空间相关。',
    accuracyNotes: previewSpatialAccuracy,
  },
  {
    id: 'spatial-gns',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.5.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '估计最完整的常见嵌套空间设定。',
    accuracyNotes: previewSpatialAccuracy,
  },
  {
    id: 'spatial-panel-sdm',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.5.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '在面板固定效应下估计空间杜宾模型。',
    accuracyNotes: previewSpatialAccuracy,
  },
  {
    id: 'spatial-logit',
    taskGroup: '空间与扩展模型',
    packId: 'experimental',
    modelVersion: '0.5.0',
    maturityLevel: 'preview',
    enabledByDefault: true,
    useCase: '估计二分类结果的空间邻近影响。',
    accuracyNotes: previewSpatialAccuracy,
  },
]

export const modelCatalogById = new Map(modelCatalog.map((entry) => [entry.id, entry]))
